workspace:
  base: /srv/app
  path: src/code.gitea.io/git

clone:
  git:
    image: plugins/git:1
    # Tests require the entire history (for some reason)
    #depth: 50
    tags: true

pipeline:
  testing:
    image: webhippie/golang:edge
    pull: true
    commands:
      - git update-ref refs/heads/test HEAD
      - make clean
      - make vet
      - make lint
      # Test with latest git version
      - git --version && make test
      # Test with git version 1.7.2
      - apk add --update autoconf zlib-dev > /dev/null &&
        mkdir build &&
        curl -sL "https://github.com/git/git/archive/v1.7.2.tar.gz" -o git.tar.gz &&
        tar -C build -xzf git.tar.gz &&
        cd build/git-1.7.2 &&
        { autoconf 2> err || { cat err && false; } } &&
        ./configure --without-tcltk --prefix=/usr/local > /dev/null &&
        { make install NO_PERL=please > /dev/null 2> err || { cat err && false; } } &&
        cd ../.. &&
        rm -rf build git.tar.gz &&
        hash -r &&
        git --version &&
        make test
      # Test a build (is this really needed?)
      - make build

  # coverage:
  #   image: plugins/coverage:1
  #   pull: true
  #   secrets: [ github_token ]
  #   server: https://coverage.gitea.io

  discord:
    image: appleboy/drone-discord:1.0.0
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]
