workspace:
  base: /srv/app
  path: src/code.gitea.io/git

clone:
  git:
    image: plugins/git:1
    # Tests require the entire history (for some reason)
    #depth: 50
    tags: true

pipeline:
  testing:
    image: webhippie/golang:edge
    pull: true
    commands:
      - git update-ref refs/heads/test HEAD
      - make clean
      - make vet
      - make lint
      - git --version
      - make test
      - apk add --update autoconf &&
        apk add --update zlib-dev &&
        mkdir build &&
        curl -sL "https://github.com/git/git/archive/v1.7.2.tar.gz" -o git.tar.gz &&
        tar -C build -xzf git.tar.gz &&
        cd build/git-1.7.2 &&
        autoconf &&
        ./configure --without-tcltk --prefix=/usr/local &&
        make install NO_PERL=please &&
        cd ../.. &&
        rm -rf build &&
        rm git.tar.gz
      - hash -r
      - git --version
      - make test
      - make build

  # coverage:
  #   image: plugins/coverage:1
  #   pull: true
  #   secrets: [ github_token ]
  #   server: https://coverage.gitea.io

  discord:
    image: appleboy/drone-discord:1.0.0
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]
